apiVersion: v1
kind: Service
metadata:
  name: linksnip-service
  namespace: linksnip
  labels:
    app: linksnip
spec:
  type: LoadBalancer
  selector:
    app: linksnip
    component: web
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: linksnip-redis
  namespace: linksnip
  labels:
    app: linksnip
    component: redis
spec:
  type: ClusterIP
  selector:
    app: linksnip
    component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
